---
title: "Workshop_ML"
author: "Abhay Singh"
date: "23/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R for Machine Learning

## Random Sampling

- Data splitting: 70:30 (70: Training; 30: Testing)

```{r}
library(quantmod)

bhp=getSymbols("BHP.AX",from="2018-01-01",to="2020-07-31",auto.assign = FALSE)
head(bhp)
d_bhp=bhp$BHP.AX.Close
head(d_bhp)
plot(d_bhp)

d_bhp=data.frame(Date=as.Date(index(d_bhp)),Price=coredata(d_bhp))
head(d_bhp)
```

- Base R for data splitting

```{r}
set.seed(999)#sets the random number generator seed

idx1=sample(1:nrow(d_bhp),round(nrow(d_bhp)*0.7))
#idx1
train1=d_bhp[idx1,]
test1=d_bhp[-idx1,]
nrow(train1)
nrow(test1)
```

### Visualisation

```{r}
library(ggplot2)
p1=ggplot(train1,aes(x=BHP.AX.Close))+geom_density(trim=TRUE,aes(color="Training"),size=1)
p1=p1+geom_density(data=test1,aes(x=BHP.AX.Close,color="Testing"),size=1,linetype=2)
```

### The caret package

```{r}
set.seed(999)

library(caret)
idx2=createDataPartition(d_bhp$BHP.AX.Close,p=0.7,list=FALSE)
train2=d_bhp[idx2,]
test2=d_bhp[-idx2,]

p2=ggplot(train2,aes(x=BHP.AX.Close))+geom_density(trim=TRUE,aes(color="Training"),size=1)
p2=p2+geom_density(data=test2,aes(x=BHP.AX.Close,color="Testing"),size=1,linetype=2)

```

### Using the rsample package

```{r}
set.seed(999)
library(rsample)
idx3=initial_split(d_bhp,prop=0.7)
train3=training(idx3)
test3=testing(idx3)


p3=ggplot(train3,aes(x=BHP.AX.Close))+geom_density(trim=TRUE,aes(color="Training"),size=1)
p3=p3+geom_density(data=test3,aes(x=BHP.AX.Close,color="Testing"),size=1,linetype=2)

```

- Arrange them all together

```{r,fig.width=10}
library(gridExtra)
grid.arrange(p1,p2,p3,nrow=1)
```


### Stratified Sampling

- Use the GermanCredit data

```{r}
set.seed(999)
data("GermanCredit")
head(GermanCredit)

idx4=initial_split(GermanCredit,prop=0.7,strata="Class")
train4=training(idx4)
test4=testing(idx4)

prop.table(table(train4$Class))
prop.table(table(test4$Class))
```


## Resampling

### K-fold Cross Validation

- rsample package

```{r}
set.seed(999)
cv1=vfold_cv(d_bhp[2],v=10)
cv1
```


- caret package

```{r}
cv2=createFolds(d_bhp$BHP.AX.Close,k=10)
cv2$Fold01
```


### Time series cross validate


```{r}
d_bhp2=xts(d_bhp$BHP.AX.Close,order.by = d_bhp$Date)
cv_ts=createTimeSlices(d_bhp2,initialWindow = 500,horizon=100,fixedWindow = TRUE)
cv_ts$train$Training500
```



### Bootstrapping

```{r}
boot1=bootstraps(d_bhp2[2],times=10)
boot1
```











